sudo: required
before_install:
  - sudo apt-get update && sudo apt-get install g++ cmake wget
  - wget https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz 
  - sudo tar -C /usr/local/ -xzf go1.5.3.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - export GOROOT=/usr/local/go
  - export GOPATH=$HOME/go
  - mkdir $HOME/go
script:
  - go vet -x ./go/...
  - golint ./go/...
  - go test -r --trace --race ./go/...
  - mkdir build && cd build && cmake .. && make test
