language: go

go:
    - 1.7.3

sudo: false

install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get github.com/stretchr/testify/assert
    - go get github.com/go-playground/overalls
    - go install github.com/go-playground/overalls
    #- go get github.com/alecthomas/gometalinter
    #- gometalinter --install

script:
    - go test -v -race ./...
    - overalls -project=github.com/vitalyisaev2/skiena -covermode=count
    - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
